#!/usr/bin/env python3
"""
Create Jira tickets from a Claude Code spec-gap report (P0/P1 only).

Idempotent: each gap has a deterministic globalId
    spec-gap-<sha256(spec_section + summary)>
A search by JQL `description ~ "globalId: <id>"` short-circuits creation if the
ticket already exists — so re-running this script on the same report is safe.

Usage
-----
  # From CI (the typical path):
  python3 scripts/jira/create-spec-gap-ticket.py \
      --gaps spec-gaps.json \
      --workflow-url "$WORKFLOW_RUN_URL"

  # Local dry-run:
  python3 scripts/jira/create-spec-gap-ticket.py --gaps spec-gaps.json --dry-run

Env (required for live mode)
---------------------------
  JIRA_BASE_URL       https://aurigraphdlt.atlassian.net (default)
  JIRA_USER_EMAIL     Atlassian account email
  JIRA_API_TOKEN      Atlassian API token
  JIRA_PROJECT_KEY    AV4 (default)

Source ticket: AV4-405 / AAT-405 (Claude Code SDK CI/CD wiring).
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


P_HIGH = {"P0", "P1"}


def env(name: str, default: str | None = None, *, required: bool = False) -> str | None:
    v = os.environ.get(name) or default
    if required and not v:
        raise SystemExit(f"Missing required env var: {name}")
    return v


def adf_for_gap(gap: dict[str, Any], *, global_id: str, workflow_url: str | None) -> dict[str, Any]:
    """Build an ADF body capturing the gap + globalId marker."""
    pretty = json.dumps(gap, indent=2, sort_keys=True)
    paragraphs: list[dict[str, Any]] = [
        {
            "type": "paragraph",
            "content": [
                {"type": "text", "text": "Auto-generated by ", "marks": []},
                {"type": "text", "text": "Claude Code spec-compliance diff", "marks": [{"type": "strong"}]},
                {"type": "text", "text": " (AV4-405 / AAT-405)."},
            ],
        },
        {
            "type": "paragraph",
            "content": [{"type": "text", "text": f"globalId: {global_id}"}],
        },
        {
            "type": "heading",
            "attrs": {"level": 3},
            "content": [{"type": "text", "text": "Gap"}],
        },
        {
            "type": "codeBlock",
            "attrs": {"language": "json"},
            "content": [{"type": "text", "text": pretty}],
        },
    ]
    if workflow_url:
        paragraphs.append({
            "type": "paragraph",
            "content": [
                {"type": "text", "text": "Workflow run: "},
                {"type": "text", "text": workflow_url, "marks": [{"type": "link", "attrs": {"href": workflow_url}}]},
            ],
        })
    return {"type": "doc", "version": 1, "content": paragraphs}


class JiraClient:
    def __init__(self, base_url: str, email: str, token: str) -> None:
        self.base_url = base_url.rstrip("/")
        raw = f"{email}:{token}".encode()
        self._auth = "Basic " + base64.b64encode(raw).decode()
        self._ctx = ssl.create_default_context()

    def request(self, method: str, path: str, body: dict | None = None) -> Any:
        url = f"{self.base_url}{path}"
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(url, data=data, method=method)
        req.add_header("Authorization", self._auth)
        req.add_header("Accept", "application/json")
        if body is not None:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, context=self._ctx, timeout=60) as resp:
                payload = resp.read().decode()
                return json.loads(payload) if payload else {}
        except urllib.error.HTTPError as e:
            err = e.read().decode()
            raise SystemExit(f"HTTP {e.code} {method} {path}: {err}") from e

    def search_existing(self, project_key: str, global_id: str) -> str | None:
        jql = f'project = "{project_key}" AND text ~ "{global_id}"'
        q = urllib.parse.urlencode({"jql": jql, "fields": "summary", "maxResults": 1})
        out = self.request("GET", f"/rest/api/3/search?{q}")
        issues = out.get("issues", [])
        if issues:
            return str(issues[0]["key"])
        return None


def gap_global_id(gap: dict[str, Any]) -> str:
    seed = (gap.get("spec_section", "") + "::" + gap.get("summary", "")).encode("utf-8")
    return "spec-gap-" + hashlib.sha256(seed).hexdigest()[:24]


def gap_summary(gap: dict[str, Any]) -> str:
    section = (gap.get("spec_section") or "spec").strip()
    summary = (gap.get("summary") or "Spec gap").strip()
    title = f"[Spec Gap] {section}: {summary}"
    return title[:240]


def load_gaps(path: Path) -> list[dict[str, Any]]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(raw, dict):
        gaps = raw.get("gaps") or raw.get("result", {}).get("gaps") or []
    else:
        gaps = raw
    if not isinstance(gaps, list):
        return []
    return [g for g in gaps if isinstance(g, dict)]


def main() -> int:
    ap = argparse.ArgumentParser(description="Create Jira tickets from Claude spec-gap report")
    ap.add_argument("--gaps", required=True, help="Path to spec-gaps.json")
    ap.add_argument("--workflow-url", default=os.environ.get("WORKFLOW_RUN_URL", ""))
    ap.add_argument("--project-key", default=os.environ.get("JIRA_PROJECT_KEY", "AV4"))
    ap.add_argument("--issue-type", default="Task")
    ap.add_argument("--labels", nargs="*", default=["spec-gap", "automated"])
    ap.add_argument("--priorities", nargs="*", default=sorted(P_HIGH),
                    help="Only create tickets for these priority values")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--sleep", type=float, default=0.25)
    args = ap.parse_args()

    path = Path(args.gaps)
    if not path.is_file():
        print(f"[skip] {path} missing")
        return 0
    gaps = load_gaps(path)
    eligible = [g for g in gaps if str(g.get("priority", "")).upper() in {p.upper() for p in args.priorities}]
    print(f"Loaded {len(gaps)} gaps; {len(eligible)} eligible (priority in {args.priorities})")
    if not eligible:
        return 0

    if args.dry_run:
        for g in eligible:
            gid = gap_global_id(g)
            print(f"[dry-run] {gid} :: {gap_summary(g)}")
        return 0

    base = env("JIRA_BASE_URL", "https://aurigraphdlt.atlassian.net", required=True)
    email = env("JIRA_USER_EMAIL", required=True)
    token = env("JIRA_API_TOKEN", required=True)
    assert base and email and token  # for type checkers
    client = JiraClient(base, email, token)

    created = 0
    skipped = 0
    for gap in eligible:
        gid = gap_global_id(gap)
        existing = client.search_existing(args.project_key, gid)
        if existing:
            skipped += 1
            print(f"[skip] {gid} already tracked as {existing}")
            time.sleep(args.sleep)
            continue
        body = {
            "fields": {
                "project": {"key": args.project_key},
                "summary": gap_summary(gap),
                "description": adf_for_gap(gap, global_id=gid, workflow_url=args.workflow_url),
                "issuetype": {"name": args.issue_type},
                "labels": list(dict.fromkeys(args.labels)),
            }
        }
        out = client.request("POST", "/rest/api/3/issue", body)
        key = out.get("key", "?")
        created += 1
        print(f"[create] {key} :: {gap_summary(gap)}  ({gid})")
        time.sleep(args.sleep)

    print(f"Done. created={created} skipped={skipped} total_eligible={len(eligible)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
